### ISSUE TITLE
latest mac os x app shows blank upon startup

### ISSUE THREAD

**Issue by HsuanTingLu** [MCS-Lite/mcs-lite-app#242]
as stated, the app shows nothing before/after starting the server

**Comment by dariachen** [comment]
Hi there, 
You have to execute the "setup" script before you launch MCS Lite on Mac machine for the 1st time. 
"setup" is at the same directory as "mcs-lite-app". 

For more detailed instruction, please refer to our user manual.
- Chinese version: https://mcs-lite-introduction.netlify.com/zh-tw/mcs_lite_intro/mcs_lite_intro.html#%E5%AE%89%E8%A3%9D%E6%8C%87%E5%8D%97
- Englinsh version: https://mcs-lite-introduction.netlify.com/en/mcs_lite_intro/mcs_lite_intro.html#installation-guide

Let us know whether this works for you. Thanks!

**Comment by HsuanTingLu** [comment]
yes I did

fyi, here's some messages from the terminal
"""
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
"""
and,
"""
nwjs[37570:10403533] *** WARNING: Textured window <AppNSWindow: 0x7fc473fcd2a0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
module.js:496
    throw err;
    ^

Error: Cannot find module './mcs-lite-app/adminServer'
    at Function.Module._resolveFilename (module.js:494:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at self.require (<anonymous>:11:26)
"""

**Comment by dariachen** [comment]
Hi @HsuanTingLu 
     Would you help us to try the sample App for NW.js? Here is the installation instruction
1. Install npm, please refer to https://docs.npmjs.com/getting-started/installing-node#apple-macos
2. Install and launch NW.js sample App
```
npm install -g nw
git clone https://github.com/zcbenz/nw-sample-apps.git
cd nw-sample-apps/file-explorer
npm start # or "nw ."
```

MCS Lite uses this module to build the application for both Mac and Windows and we would like to identify if there is any compatibility issue in this module. Because we can't reproduce this issue on our own Mac machine, it will be helpful if you or someone encountering this issue can help us to narrow down the problem.

**Comment by HsuanTingLu** [comment]
yes the sample app launched successfully

**Comment by dariachen** [comment]
Hi @HsuanTingLu 
     We saw a similar issue about NW.js https://github.com/nwjs/nw.js/issues/6238. It might be caused by Chromium and not be resolved yet. 

     However, we would still like to do more investigation on this issue. Would you mind to provide some more detailed information to us? We appreciate your participation and support!

1. Model name
2. OS version: macOS High Sierra Version 10.13.2?
3. Reproduce steps and error message at each step (launch App directly by clicking the icon or use the command line?)

**Comment by HsuanTingLu** [comment]
Model Name:	MacBook Air Early 2014
Model Identifier:	MacBookAir6,2
OS: macOS High Sierra Version 10.13.2

HOMEBREW_VERSION: 1.4.2-4-g069b610
node -v: v9.3.0
npm -v: 5.6.0

downloaded latest release (v1.2.2): osx64.tar.gz

### setup
(under osx64/)
```
$ ./setup
.
```

### fresh nw install
(under osx64/)
```
$ npm i -g nw
...
$ nw --version
nwjs 63.0.3239.132
```

### mouse click
(double clicked .app file to launch)
(blank window)


### command line open
(under osx64/)
```
$ open mcs-lite-app.app/
```
(blank window)


### nwjs direct execute
(under osx64/)
```
$ cd mcs-lite-app.app/Contents/MacOS
$ ./nwjs
err = 3 ../../third_party/mach_override/mach_override.c:244
err = 3 ../../third_party/mach_override/mach_override.c:258
err = 3 ../../third_party/mach_override/mach_override.c:263
err = 3 ../../third_party/mach_override/mach_override.c:244
err = 3 ../../third_party/mach_override/mach_override.c:258
err = 3 ../../third_party/mach_override/mach_override.c:263
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
err = 3 ../../third_party/mach_override/mach_override.c:244
err = 3 ../../third_party/mach_override/mach_override.c:258
err = 3 ../../third_party/mach_override/mach_override.c:263
2018-01-09 17:25:48.461 nwjs[53752:1814777] *** WARNING: Textured window <AppNSWindow: 0x7fe12c27adc0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
module.js:496
    throw err;
    ^

Error: Cannot find module './mcs-lite-app/adminServer'
    at Function.Module._resolveFilename (module.js:494:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at self.require (<anonymous>:11:26)
```
(with blank window)

**Comment by dariachen** [comment]
Hi @HsuanTingLu, 
     It looks like the setup script was not executed successfully at this step.

```
$ ./setup
.
```
    Please try to either right-click on the setup file -> choose open or use open command to launch it. 

```
$ open setup
```
PS: You might see a security warning while it is launched, please just click "OK".
![](https://mcs-lite-introduction.netlify.com/assets/unknown_warning.png)

**Comment by HsuanTingLu** [comment]
problem resolved, thank you
